
# This workflow will inspect a pull request to ensure there is a linked issue or a
# valid issue is mentioned in the body. If neither is present it fails the check and adds
# a comment alerting users of this missing requirement.
name: Test

on:
  push:
    branches:
      - main


jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: View the information of the pusher
        run: |
          echo "The name of the pusher: ${{ github.event.pusher.name }}"
          echo "The email of the pusher: ${{ github.event.pusher.email }}"
      - name: Expose git commit data
        uses: rlespinasse/git-commit-data-action@v1

      - name: Print git commit data
        run: |
          echo "Get commit info"
          echo " - ${{ env.GIT_COMMIT_SHA }}"
          echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
          echo "Get author info"
          echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
          echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
          echo "Get committer info"
          echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
          echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
          echo "Get message info"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
          echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"
      - name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        with:
          mage_size: 30
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      - name: check on first merged pull requests
        uses: sukki37/new-pull-request-comment-action@v0.1.1

        id: first-check
        with:
          message: 'hello world!'
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
      - name: Run scheduled task
        run: |
          echo 'Adding this ${{ github.event.pull_request.user.login }} to Contributors...'
          echo 'first-check output is ${{ steps.first-check.outputs.is_first_pr }}'
